version: "3"

tasks:
  default:
    cmd: task -l --sort none
    silent: true

  test:
    desc: "Run tests"
    cmds:
      - uv run pytest -v

  generate_output:
    desc: "Generate test output"
    aliases: [gen]
    cmds:
      - uv run python convert_poetry2uv.py tests/files/poetry_pyproject.toml -n
      - cat tests/files/pyproject_temp_uv.toml

  cov:
    desc: "Run tests with coverage"
    cmds:
      - uv run pytest --cov=convert_poetry2uv --cov-report html tests/ -v

  new_uv_pyproject:
    desc: "Create a uv_pyproject toml file for tests"
    aliases: [new_uv]
    cmds:
      - uv run python convert_poetry2uv.py tests/files/poetry_pyproject.toml -n
      - mv tests/files/pyproject_temp_uv.toml tests/files/uv_pyproject.toml

  build:
    desc: "Build the project"
    cmds:
      - uv build

  clean:
    desc: "Clean the project"
    cmds:
      - rm -rf convert_poetry2uv.egg-info
      - rm -rf dist
