version: "3"

tasks:
  default:
    cmd: task -l --sort none
    silent: true

  test:
    desc: "Run tests"
    cmds:
      - uv run pytest -v

  generate_output:
    desc: "Generate test output"
    aliases: [gen]
    cmds:
      - uv run python convert_poetry2uv.py tests/files/poetry_pyproject.toml -n
      - cat tests/files/pyproject_temp_uv.toml

  cov:
    desc: "Run tests with coverage"
    cmds:
      - uv run pytest --cov=convert_poetry2uv --cov-report html tests/ -v

  new_uv_pyproject:
    desc: "Create a uv_pyproject toml file for tests"
    aliases: [new_uv]
    cmds:
      - uv run python convert_poetry2uv.py tests/files/poetry_pyproject.toml -n
      - mv tests/files/pyproject_temp_uv.toml tests/files/uv_pyproject.toml

  build:
    desc: "Build the project"
    cmds:
      - uv build

  clean_build:
    desc: "Clean the project"
    cmds:
      - rm -rf convert_poetry2uv.egg-info
      - rm -rf dist

  release:
    desc: "Release the project"
    cmds:
      - uv run semantic-release version --skip-build --no-vcs-release --no-changelog --no-push --no-commit

  # bump:patch:
  #   desc: "Update the patch version and tag"
  #   cmds:
  #     - uv run bumpversion patch
  #     - task: bump:sync_and_tag

  # bump:minor:
  #   desc: "Update the minor version and tag"
  #   cmds:
  #     - uv run bumpversion minor
  #     - task: bump:sync_and_tag

  # bump:sync_and_tag:
  #   desc: "Update the version and tag"
  #   internal: true
  #   cmds:
  #     - uv sync
  #     - git commit uv.lock -m "Updated uv.lock"
  #     - |
  #       echo "Type the message you want to add to the tag?"
  #       read MESSAGE
  #       git tag -a $(cat .bumpversion.cfg | grep "current_version = " | awk '{print $3}') -m "${MESSAGE}"

  push:
    desc: "Push to git with tags"
    cmds:
      - git push --tags